import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-white">
  <nav className="p-6 flex justify-between border-b border-gray-700">
    <h1 className="font-bold text-xl">Dr. Vignesh Kumar C</h1>
    <div className="space-x-6">
      <a href="/">Home</a>
      <a href="/about">About</a>
<a href="/research">Research</a>
      <a href="/experience">Experience</a>
      <a href="/projects">Projects</a>
      
      <a href="/contact">Contact</a>
    </div>
  </nav>
  {children}
</body>
    </html>
  );
}
